version: 1

consol_log:
  level: DEBUG

formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  log_handler:
    class: logging.FileHandler
    filename: clfit.log
    level: DEBUG
    formatter: simple

  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: cfg://consol_log.level
    formatter: simple

loggers:
  clfit:
    level: DEBUG
    handlers: [log_handler]
    propagate: yes

root:
  level: DEBUG
  handlers: [stream_handler]
