apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference-probes
spec:
  containers:
    - image: kbrodt/online_inference:v2
      name: online-inference-probes
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: 64Mi
          cpu: 200m
        limits:
          memory: 128Mi
          cpu: 250m
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 15
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
