input_data_path: "data/raw/heart.csv"
logging_path: "configs/logging.conf.yml"
experiment_path: "models/logreg"
output_model_fname: "model.pkl"
metric_fname: "metrics.json"
test_data_path: "data/raw/heart.csv"
predict_path: "models/logreg/predicts.csv"

splitting_params:
  test_size: 0.1
  seed: 314159

train_params:
  model_type: "LogisticRegression"
  params:
    random_state: 42

feature_params:
  feature_pipelines:
    - name: "numeric"
      pipelines:
        - name: "SimpleImputer"
          params:
            strategy: "mean"
        - name: "StandardScaler"
      columns:
        - "age"
        - "trestbps"
        - "chol"
        - "thalach"
        - "oldpeak"

    - name: "log1p"
      pipelines:
        - name: "Log1p"
        - name: "StandardScaler"
      columns:
        - "trestbps"
        - "oldpeak"

    - name: "categorical"
      pipelines:
        - name: "OneHotEncoder"
      columns:
        - "cp"
        - "restecg"
        - "slope"
        - "ca"
        - "thal"

    - name: "binary"
      pipelines: "passthrough"
      columns:
        - "sex"
        - "fbs"
        - "exang"

  target_col: "target"
